config1:
  filename: D:\Diffusivity calculation\Raw data\H2 raw data.xlsx
  rso: 126.9
  amembrane: 5.73
  gas: H2
config2:
  filename:
  rso:
  amembrane:
  gas:
config3:
  filename:
  rso:
  amembrane:
  gas:
config4:
  filename:
  rso:
  amembrane:
  gas:
config5:
  filename:
  rso:
  amembrane:
  gas:
fileformat: csv
outputfile: output
